"""The fixed list of state names and fault reasons."""

class State:
    INIT = "INIT"
    IDLE = "IDLE"
    PRECHARGE = "PRECHARGE"
    DRIVE = "DRIVE"
    CHARGING = "CHARGING"
    DISCHARGE = "DISCHARGE"
    FAULT = "FAULT"

ALL_STATES = (
    State.INIT,
    State.IDLE,
    State.PRECHARGE,
    State.DRIVE,
    State.CHARGING,
    State.DISCHARGE,
    State.FAULT,
)


HV_CONNECTED_STATES = frozenset({State.PRECHARGE, State.DRIVE, State.CHARGING})

class FaultReason:
    """Why the machine entered FAULT."""

    CELL_UNDERVOLTAGE = "CELL_UNDERVOLTAGE"
    CELL_OVERVOLTAGE = "CELL_OVERVOLTAGE"

    CELL_OVERTEMP = "CELL_OVERTEMP"
    CELL_UNDERTEMP = "CELL_UNDERTEMP"

    OVERCURRENT_DISCHARGE = "OVERCURRENT_DISCHARGE"
    OVERCURRENT_CHARGE = "OVERCURRENT_CHARGE"

    SENSOR_MISSING = "SENSOR_MISSING"
    SENSOR_IMPLAUSIBLE = "SENSOR_IMPLAUSIBLE"
    SENSOR_STALE = "SENSOR_STALE"

    PRECHARGE_TIMEOUT = "PRECHARGE_TIMEOUT"
    DISCHARGE_TIMEOUT = "DISCHARGE_TIMEOUT"


ALL_FAULT_REASONS = (
    FaultReason.CELL_OVERVOLTAGE,
    FaultReason.CELL_UNDERVOLTAGE,
    FaultReason.CELL_OVERTEMP,
    FaultReason.CELL_UNDERTEMP,
    FaultReason.OVERCURRENT_DISCHARGE,
    FaultReason.OVERCURRENT_CHARGE,
    FaultReason.SENSOR_MISSING,
    FaultReason.SENSOR_IMPLAUSIBLE,
    FaultReason.SENSOR_STALE,
    FaultReason.PRECHARGE_TIMEOUT,
    FaultReason.DISCHARGE_TIMEOUT,
)
